logging:
  level:
    org:
      springframework:
        security:
          saml: DEBUG
      opensaml: DEBUG
    com:
      spring:
        boot:
          security:
            saml: DEBUG

service.provider.entity.id: com:phuta:spring:boot:sp

idp.metedata.url: /Users/phuta.local/Downloads/saml2-metadata-idp.xml

# you can update credentials if you want, I recommend you to keep as it is for demo purpose
saml:
  keystore.password: nalle123
  private.key:
    alias: apollo
    password: nalle123