logging:
  level:
    org:
      springframework:
        security:
          saml: DEBUG
      opensaml: DEBUG
    com:
      spring:
        boot:
          security:
            saml: DEBUG

service.provider.entity.id: com:spring:boot:sp:${server.port}

idp.metadata.url: /Users/phuta/Downloads/saml2-metadata-idp-${server.port}.xml

# you can update credentials if you want, I recommend you to keep as it is for demo purpose
saml:
  keystore.password: nalle123
  private.key:
    alias: apollo
    password: nalle123

server:
  port: 8443
  servlet:
    session:
      cookie:
        name: COOKIE${server.port}